### ISSUE TITLE
subtraction doesnt work with string numbers

### ISSUE THREAD

**Issue by georgiepayne** [stchang/450lang#11]
**Example That Shows the Bug**
```
(- "2" "1") 
```
**Expected Result**
1

**Actual (Incorrect) Result**
NaN

**Additional Information**
```(- "2" "1")``` should have an implicit string->num conversion and evaluate to 1.

**Comment by stchang** [comment]
The example does demonstrate a bug, but not for the stated reason. It's because the result differs from JS coercion semantics, which `450lang` follows. (So the title, Expected result, and Additional information are incorrect, could you fix please?)

More specifically, `"2"-"1"` "works" and evaluates to 1 in JS because of the implicit string->num coercion. So the expected result should be 6 ([check it here](https://repljs.com/new?local=d5f74e10-7c03-4af7-bfb0-2e79de6f66f0))

**Comment by stchang** [comment]
Title should not mention implementation details so I updated it again

Also, the example should be minimal. So get can you get rid of the `+` part

**Comment by stchang** [comment]
Fixed, thanks again!
