### ISSUE TITLE
Comparison With Zero Arguments Error

### ISSUE THREAD

**Issue by p-laskey** [stchang/450lang#20]
**Example That Shows the Bug**
(chk= (<) #true)

**Expected Result**
< #true = #t

**Actual (Incorrect) Result**
< #true = Error, contract violation

**Additional Information**
In standard Racket, a comparison expression with no arguments will return true, as seen in this example. The very same expression gives an error in 450lang. While it is an odd line of code to run, 450lang does in fact produce a bug compared to regular Racket which does not.

**Comment by stchang** [comment]
Hi thanks for the report. But submitted issues must follow the posted instructions.  In particular, the "actual" result should report what actually happens when the program runs (please do run the example before submitting). 

In this case, running the program produces: `parse: not a valid CS450 Lang program in: #t` which is the correct behavior.
